
name: Blog Console CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run:
          sudo npm install gitbook-cli -g;
          gitbook install;
          gitbook build;
