
name: Blog Console CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run:
          sudo npm install gitbook-cli -g;
          echo '------------install gitbook-cli 0k-----------------------';
          which gitbook;
          echo '-----------------------------------';
          /usr/local/bin/gitbook install;
